# nameOverride: ""
provider: entercloudsuite

# supported kubernetes versions: 1.13.5, 1.14.1 or 1.14.3
version: 1.14.1

# use versionOverride just for upgrading the master
cluster:
  replicas: 3
  vcpu: 2
  ram: 4  
  versionOverride: 1.14.3

# use versionOverride just for upgrading the nodes
nodepools:
  - name: pool1
    replicas: 1
    vcpu: 2
    ram: 2  
    autoscaler:
      enabled: true
      max: 5
