apiVersion: v1
kind: Pod
metadata:
  name: {{ include "serviceName" . }}-balancer
  labels:
    app: {{ include "serviceName" . }}-balancer
    helm.sh/chart: {{ include "example.chart" . }}
    app.kubernetes.io/part-of: {{ include "example.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  containers:
    - name: {{ include "serviceName" . }}-haproxy
      image: haproxy
      volumeMounts:
      - name: {{ include "serviceName" . }}-config-volume
        mountPath: /usr/local/etc/haproxy/
  volumes:
    - name: {{ include "serviceName" . }}-config-volume
      configMap:
        name: {{ include "serviceName" . }}-config