apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "serviceName" . }}-config
  labels:
    helm.sh/chart: {{ include "example.chart" . }}
    app.kubernetes.io/part-of: {{ include "example.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  haproxy.cfg: |-
    defaults
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 8000
        timeout client  60000
        timeout server  60000
        default-server init-addr last,libc,none

    resolvers dns-consul
      nameserver dns1 {{ .Values.balancer.dns }}:53
      hold valid 1s

    frontend app
        bind *:80
        mode http
        maxconn 256
        default_backend example
        stats uri     /stats
        stats refresh 10s
        stats realm   Haproxy\ Statistics
        stats hide-version
        stats show-desc "HAProxy WebStatistics"
        stats show-node
        stats show-legends
        stats auth {{ .Values.balancer.username }}:{{ .Values.balancer.password }}
        stats admin if TRUE

    backend example
        mode http
        balance source
        option tcpka
        server-template example 5 example.service.automium.consul:8080 check port 8080 resolvers dns-consul