apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioner-config
  labels:
    helm.sh/chart: {{ include "example.chart" . }}
    app.kubernetes.io/part-of: {{ include "example.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}