kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "serviceName" . }}-rolebinding
  labels:
    helm.sh/chart: {{ include "example.chart" . }}
    app.kubernetes.io/part-of: {{ include "example.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ include "serviceName" . }}-role
  apiGroup: rbac.authorization.k8s.io