apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceName" . }}-serviceaccount
  labels:
    helm.sh/chart: {{ include "example.chart" . }}
    app.kubernetes.io/part-of: {{ include "example.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}